In [1]:
import numpy as np

In [13]:
v1 = np.array([16,6,7])
v2 = np.array([11,7,22])

print(v1 + v2)
print(v1 * v2)
print(v1 - v2)
v1.dot (v2)
v1.shape

[27 13 29]
[176  42 154]
[  5  -1 -15]


(3,)

In [16]:
m1 =np.array([[22,10,7,],
             [11,12,13],
             [22,1,3]])
m1.shape
print(m1.nidm)
print(m1.shape)

AttributeError: 'numpy.ndarray' object has no attribute 'nidm'

In [17]:
import numpy as np

vec = np.array([1, 2, 3, 4, 5, 6])
mat = vec.reshape((3, 2))
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
import numpy as np

vec = np.array([1, 2, 3, 4])
(vec.shape[0], 1)


(4, 1)

In [21]:
mat = vec.reshape((vec.shape[0], 1))
mat

array([[1],
       [2],
       [3],
       [4]])

In [22]:
mat = np.array([[1.1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(mat.dtype) 



float64


In [23]:
x = 3.5
print(type(x)) 

<class 'float'>


In [27]:
class c:
        x=3
c1 =c()

In [28]:
mat = np.array([[c1, 8],
                [3, 2]])

print(mat)
mat.dtype

[[<__main__.c object at 0x000001F21EE38C50> 8]
 [3 2]]


dtype('O')

In [29]:
mat = np.array([[1, 2, 3],
                [4, "5", 6],
                [7, 8, 9]])

float_matrix = mat.astype(float)
print(float_matrix)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
