In [2]:
import numpy as np

In [8]:
v1 = np.array([16,6,7])
v2 = np.array([11,7,22])

print(v1 + v2)
print(v1 * v2)
print(v1 - v2)
v1.dot(v2)
v1.shape

[27 13 29]
[176  42 154]
[  5  -1 -15]


(3,)

In [7]:
m1 =np.array([[22,10,7,],
            [11,12,13],
            [22,1,3]])
m1.shape
print(m1.ndim)
print(m1.shape)

2
(3, 3)


In [17]:
import numpy as np

vec = np.array([1, 2, 3, 4, 5, 6])
mat = vec.reshape((3, 2))
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
import numpy as np

vec = np.array([1, 2, 3, 4])
(vec.shape[0], 1)


(4, 1)

In [21]:
mat = vec.reshape((vec.shape[0], 1))
mat

array([[1],
       [2],
       [3],
       [4]])

In [22]:
mat = np.array([[1.1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(mat.dtype) 



float64


In [23]:
x = 3.5
print(type(x)) 

<class 'float'>


In [27]:
class c:
        x=3
c1 =c()

In [28]:
mat = np.array([[c1, 8],
                [3, 2]])

print(mat)
mat.dtype

[[<__main__.c object at 0x000001F21EE38C50> 8]
 [3 2]]


dtype('O')

In [29]:
mat = np.array([[1, 2, 3],
                [4, "5", 6],
                [7, 8, 9]])

float_matrix = mat.astype(float)
print(float_matrix)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [9]:
pip install tkintertable


  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  Created wheel for tkintertable: filename=tkintertable-1.3.3-py3-none-any.whl size=66248 sha256=53346eac44fee136e31c6b08403f83e4e124cb31c483c9c15ff78593154ce6eb
  Stored in directory: c:\users\ahmed\appdata\local\pip\cache\wheels\93\b5\2d\e0c1d9fad21eeab6171702bc918627821cb2c46aecc7e69bb9
Successfully built tkintertable

   ---------------------------------------- 0/2 [future]
   ---------------------------------------- 0/2 [future]
   ---------------------------------------- 0/2 [future]
   ---------------------------------------- 0/2 [future]
   ---------------------------------------- 0/2 [future]
   ---------------------------------------- 0/2 [future]
   -


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
