In [1]:
import pandas as pd

In [2]:
s = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s

a    1
b    2
c    3
d    4
dtype: int64

In [3]:
data = [[1, 444, 'abc'],
        [2, 555, 'def'],
        [3, 666, 'ghi'],
        [4, 444, 'xyz']
]

df = pd.DataFrame(data, columns=['id', 'salary', 'dept'])
df

,id,salary,dept
0,1,444,abc
1,2,555,def
2,3,666,ghi
3,4,444,xyz


In [4]:
data_dic = {
    'id': [1, 2, 3, 4], 
    'salary': [444, 555, 666, 444],
    'dept': ['abc', 'def', 'ghi', 'x']
}

df = pd.DataFrame(data_dic)
print(df)

   id  salary dept
0   1     444  abc
1   2     555  def
2   3     666  ghi
3   4     444    x


In [5]:
data = [[1, 444, 'abc'],
        [2, 555, 'def'],
        [3, 666, 'ghi'],
        [4, 444, 'xyz']
]

df = pd.DataFrame(data, columns=['id', 'salary', 'dept'])
display(df)  

,id,salary,dept
0,1,444,abc
1,2,555,def
2,3,666,ghi
3,4,444,xyz


In [6]:
data = [[1, 444, 'abc'],
        [2, 555, 'def'],
        [3, 666, 'ghi'],
        [4, 444, 'xyz']
]

df = pd.DataFrame(data, columns=['id', 'salary', 'dept'])
df = pd.DataFrame(data, columns=['id', 'salary', 'dept'])
display(df)
x = df.columns
index = ['R1', 'R2', 'R3', 'R4']
df.index = index
df

,id,salary,dept
0,1,444,abc
1,2,555,def
2,3,666,ghi
3,4,444,xyz


,id,salary,dept
R1,1,444,abc
R2,2,555,def
R3,3,666,ghi
R4,4,444,xyz


In [7]:
df.dtypes

id         int64
salary     int64
dept      object
dtype: object

In [8]:
def chk(df, ty):
    return df[ty].dtype

In [9]:
df['dept'].dtype

dtype('O')

In [10]:
df['id'].dtype

dtype('int64')

In [11]:
df['dept'] = df['dept'].astype('category')

In [12]:
df.dtypes

id           int64
salary       int64
dept      category
dtype: object

In [13]:
df.describe()

,id,salary
count,4.000000,4.000000
mean,2.500000,527.250000
std,1.290994,106.274409
min,1.000000,444.000000
25%,1.750000,444.000000
50%,2.500000,499.500000
75%,3.250000,582.750000
max,4.000000,666.000000


In [14]:
df.describe(include='category')

,dept
count,4
unique,4
top,abc
freq,1


In [15]:
df.index

Index(['R1', 'R2', 'R3', 'R4'], dtype='object')

In [16]:
df.columns

Index(['id', 'salary', 'dept'], dtype='object')

In [17]:
df['salary'].unique()

array([444, 555, 666])

In [18]:
df['salary'].nunique()

3

In [19]:
df['salary'].sum()

np.int64(2109)

In [20]:
df['salary'].values

array([444, 555, 666, 444])

In [21]:
df.values

array([[1, 444, 'abc'],
       [2, 555, 'def'],
       [3, 666, 'ghi'],
       [4, 444, 'xyz']], dtype=object)

In [22]:
df.replace(555, 'Ali')

,id,salary,dept
R1,1,444,abc
R2,2,Ali,def
R3,3,666,ghi
R4,4,444,xyz
