# NumPy Programming Assignment

Part 1: Smart Array Factory
Task: Create a function that allows students to generate specific array types quickly using built-in NumPy methods.


In [ ]:
import numpy as np

def array_factory(mode, shape, value=None):
    if mode == 'zeros':
        return np.zeros(shape)
    if mode == 'ones':
        return np.ones(shape)
    if mode == 'full':
        return np.full(shape, value)
    if mode == 'identity':
        return np.eye(shape)

Part 2: The secure_reshape_and_stack Function.

This function demonstrates how to handle data integration by transforming a flat data structure into a matrix and then combining it with an existing dataset

In [3]:
import numpy as np

def secure_reshape_and_stack(data1, data2, new_shape):
    """
    1. Validates and converts inputs to NumPy arrays.
    2. Reshapes the first dataset to a specific dimension.
    3. Vertically stacks both datasets into one matrix.
    """
    try:
        # Convert inputs to ndarray to ensure they are processed as Tensors 
        arr1 = np.array(data1)
        arr2 = np.array(data2)

        # Rule: Change the shape of arr1 to new_shape 
        # Turning a vector (1D) into a matrix (2D)
        reshaped_arr1 = arr1.reshape(new_shape)

        # Rule: Vertical Stacking (vstack) 
        # Both matrices must have the same number of columns
        combined_dataset = np.vstack((reshaped_arr1, arr2))

        return combined_dataset

    except ValueError as e:
        # Handle cases where reshape size doesn't match or stack columns don't match
        raise ValueError(f"Company-grade Error: {e}")


part-3 The apply_threshold Function.

This function demonstrates Conditional Access and Modification, which are primarily used in data cleaning and processing. It follows the logic of identifying specific elements based on a boolean condition and replacing them efficiently.

In [4]:
import numpy as np

def apply_threshold(arr, threshold, replacement_value=-1):
    """
    Finds elements satisfying a condition (>= threshold) 
    and replaces them with a new value.
    """
    # 1. Convert input to a numpy array (ndarray)
    arr = np.array(arr)
    
    # 2. Define the condition: elementwise comparison 
    # This creates a Boolean numpy array (True where condition is met)
    condition = (arr >= threshold)
    
    # 3. Apply Modification using np.where() 
    # Logic: if condition is True, use replacement_value; else, keep original value
    modified_arr = np.where(condition, replacement_value, arr)
    
    return modified_arr


TestCase

In [6]:
import numpy as np

branch_a = [1, 2, 3, 4, 5, 6]
branch_b = [[7, 8, 9],
            [10, 11, 12]]

def secure_reshape_and_stack(data1, data2, new_shape):
    arr1 = np.array(data1)
    arr2 = np.array(data2)
    reshaped_arr1 = arr1.reshape(new_shape)
    return np.vstack((reshaped_arr1, arr2))

final_report = secure_reshape_and_stack(branch_a, branch_b, (2, 3))
print(final_report)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
v= np.array([1,2,3])
apply_threshold(v,2,-20)


array([  1, -20, -20])